export const fallbackData = {
  campaign: "Diario operativo — Campagna D&D",
  currentArc: "Atto II",
  lastUpdated: "Sessione 1 consolidata",
  summary:
    "Il party è tornato a Candlekeep dopo la battaglia al Tempio di Selûne. La sessione ha consolidato il passaggio all’Atto II: cure, debriefing, avanzamento al 9° livello, Jal maledetto, decisione strategica tra Westgate e Mare della Luna/Elventree, evoluzione personale di Wilhelm, Pedri e lettera ad Hanna.",
  sessions: [
    {
      session_id: "A2-S1",
      atto: "II",
      sessione: 1,
      titolo: "Ritorno a Candlekeep e biforcazione dei frammenti",
      data_in_game: "Subito dopo la battaglia esterna al Tempio di Selûne",
      luogo: "Candlekeep",
      livello_party: 9,
      stato: "Conclusa",
      sintesi:
        "Il party torna a Candlekeep tramite l’elfo biondo, svolge debriefing, riceve cure da Kei Tigersteel, si riposa, prepara la scelta tra Westgate e Mare della Luna/Elventree. Jal è maledetto e incapace; Pedri diventa seguace volontario di Wilhelm; Wilhelm invia una lettera ad Hanna.",
    },
  ],
  events: [
    {
      event_id: "A2-S1-E01",
      session_id: "A2-S1",
      ordine: 1,
      tipo: "Riepilogo",
      titolo: "Ricapitolazione Atto I",
      descrizione:
        "DM e giocatori ricostruiscono insieme gli eventi dall’inizio della campagna fino alla fine dell’Atto I, incluse le morti di Ares e Nicodemus.",
      luogo: "Fuori gioco",
      pg_coinvolti: "Tutto il party",
      png_coinvolti: "",
      fazioni: "",
      noto_ai_pg: true,
      segreto_dm: false,
      conseguenze: "Continuity condivisa consolidata.",
      tag: "Continuity, Atto I",
      stato: "Chiuso",
      note_dm: "",
    },
    {
      event_id: "A2-S1-E02",
      session_id: "A2-S1",
      ordine: 2,
      tipo: "Arrivo",
      titolo: "Teletrasporto a Candlekeep",
      descrizione:
        "Il party arriva a Candlekeep grazie al teletrasporto dell’elfo biondo, ancora sporco, ferito ed esausto dopo la battaglia.",
      luogo: "Candlekeep",
      pg_coinvolti: "Tutto il party",
      png_coinvolti: "Elfo biondo, Jal",
      fazioni: "Candlekeep, Arpisti",
      noto_ai_pg: true,
      segreto_dm: false,
      conseguenze: "Avvio della fase di debriefing e cura.",
      tag: "Candlekeep, Atto II",
      stato: "Chiuso",
      note_dm: "",
    },
    {
      event_id: "A2-S1-E03",
      session_id: "A2-S1",
      ordine: 3,
      tipo: "Scelta",
      titolo: "Piste Westgate e Mare della Luna",
      descrizione:
        "Saviskas, Agal e Matreus presentano le piste: Westgate con baule ritrovato e agenti spariti; Mare della Luna con risposta magica parziale e contatto interrotto.",
      luogo: "Candlekeep",
      pg_coinvolti: "Tutto il party",
      png_coinvolti: "Saviskas, Agal, Matreus",
      fazioni: "Arpisti",
      noto_ai_pg: true,
      segreto_dm: true,
      conseguenze:
        "Il party deve decidere entro 1-2 giorni. Segreto DM: frammento Westgate rubato, rivelazione a Iriaebor.",
      tag: "Westgate, Elventree, Iriaebor",
      stato: "Aperto",
      note_dm: "Correggere sempre: i PG non sanno ancora del furto del frammento.",
    },
  ],
  characters: [
    {
      nome: "Wilhelm De Wundt",
      tipo: "PG",
      stato: "Attivo",
      livello: 9,
      luogo: "Candlekeep",
      fazione: "Casata De Wundt",
      relazioni: "Elowen; Pedri; Hanna; Sigmund; Abraham Graniodor",
      noto_ai_pg: true,
      segreto_dm: false,
      note: "Capitano; baule ritrovato a Westgate; lettera inviata ad Hanna.",
    },
    {
      nome: "Jal",
      tipo: "PNG",
      stato: "Maledetto, incapace",
      livello: "",
      luogo: "Candlekeep",
      fazione: "Shar / party",
      relazioni: "Party; Matreus",
      noto_ai_pg: true,
      segreto_dm: true,
      note: "Rischio morte e rinascita come non morto ostile se non curato.",
    },
    {
      nome: "Pedri",
      tipo: "PNG",
      stato: "Seguace volontario di Wilhelm",
      livello: 3,
      luogo: "Candlekeep",
      fazione: "Casata De Wundt",
      relazioni: "Wilhelm",
      noto_ai_pg: true,
      segreto_dm: false,
      note: "Guerriero 3; affetto/devozione platonica per Wilhelm.",
    },
  ],
  questions: [
    {
      id: "QA-001",
      area: "Scelta strategica",
      domanda: "Il party sceglierà Westgate o Mare della Luna/Elventree?",
      priorita: "Alta",
      stato: "Aperta",
      sessione_origine: "A2-S1",
      noto_ai_pg: true,
      segreto_dm: false,
      note: "Decisione entro 1-2 giorni in-game.",
    },
  ],
  info: [
    {
      id: "INFO-001",
      informazione: "Il frammento di Westgate è già stato rubato.",
      stato: "Oggettivo DM",
      noto_a: "DM / Arpisti, non ancora PG",
      quando_rivelare: "Iriaebor",
      sessione_origine: "A2-S1",
      note: "Non anticipare nella sintesi per i PG.",
    },
  ],
  diaryExtended: [],
  attachments: [],
};
